# Generated by Django 4.2.3 on 2023-07-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='name',
            field=models.CharField(default=1, max_length=60, verbose_name='prosto name'),
            preserve_default=False,
        ),
    ]
