# Generated by Django 4.2.3 on 2023-07-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_logo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='karusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='karusel title')),
                ('name', models.CharField(max_length=60, verbose_name='karusel name')),
                ('info', models.TextField(verbose_name='karusel info')),
                ('button_name', models.CharField(max_length=60, verbose_name='karusel button_name')),
                ('img1', models.ImageField(upload_to='my_images', verbose_name='karusel image1')),
            ],
        ),
    ]
