# Generated by Django 4.2.3 on 2023-07-20 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_passive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passive',
            name='passive',
        ),
        migrations.AddField(
            model_name='karusel',
            name='passive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.passive'),
            preserve_default=False,
        ),
    ]
