# Generated by Django 4.2.3 on 2023-07-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_passive_passive_karusel_passive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karusel',
            name='passive',
        ),
        migrations.DeleteModel(
            name='Passive',
        ),
    ]
