# Generated by Django 4.2.3 on 2023-07-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_category_product_proproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
