# Generated by Django 4.2.3 on 2023-07-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.AddField(
            model_name='proproduct',
            name='logo',
            field=models.ImageField(blank=True, upload_to='home_proImage', verbose_name='Product image'),
        ),
    ]
