# Generated by Django 4.2.3 on 2023-07-30 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_brand_proproduct_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proProds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_cart', to='main.proproduct')),
            ],
        ),
    ]
