# Generated by Django 4.2.3 on 2023-08-02 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='SubCategory name')),
                ('name_hy', models.CharField(max_length=60, null=True, verbose_name='SubCategory name')),
                ('name_ru', models.CharField(max_length=60, null=True, verbose_name='SubCategory name')),
                ('name_en', models.CharField(max_length=60, null=True, verbose_name='SubCategory name')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
            },
        ),
        migrations.RemoveField(
            model_name='cart',
            name='proProds',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='cart',
            name='prod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=1, upload_to='images', verbose_name='Product image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Product logo'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_hy',
            field=models.CharField(max_length=80, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Product price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Product name'),
        ),
        migrations.DeleteModel(
            name='proProduct',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.subcategory'),
            preserve_default=False,
        ),
    ]
